language: java

jdk:
    - oraclejdk8

services:
    - mysql

before_install:
    - mysql -uroot -e "grant all on tabok.* to tabok@localhost identified by 'W3knd1cT4b0Db'"
    - mysql -uroot -e "drop database if exists tabok"
    - mysql -uroot -e "create database tabok"

after_success:
    - mvn jacoco:report coveralls:report

deploy:
    provider: openshift
    user: fadhlan.fdln@gmail.ccom
    password:
        secure: lutf1g1thub83
    app: belajar
    domain: fadhlan
    on:
        repo: fdln/belajar-ci
